# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zahyrseferina/CLionProjects/node-connector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zahyrseferina/CLionProjects/node-connector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zahyrseferina/CLionProjects/node-connector/CMakeFiles /home/zahyrseferina/CLionProjects/node-connector//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zahyrseferina/CLionProjects/node-connector/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zahyrseferina/CLionProjects/node-connector/CMakeFiles /home/zahyrseferina/CLionProjects/node-connector//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zahyrseferina/CLionProjects/node-connector/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named node_connector

# Build rule for target.
node_connector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node_connector
.PHONY : node_connector

# fast build rule for target.
node_connector/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/build
.PHONY : node_connector/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/modules/core/Core.o: src/modules/core/Core.cpp.o
.PHONY : src/modules/core/Core.o

# target to build an object file
src/modules/core/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/core/Core.cpp.o
.PHONY : src/modules/core/Core.cpp.o

src/modules/core/Core.i: src/modules/core/Core.cpp.i
.PHONY : src/modules/core/Core.i

# target to preprocess a source file
src/modules/core/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/core/Core.cpp.i
.PHONY : src/modules/core/Core.cpp.i

src/modules/core/Core.s: src/modules/core/Core.cpp.s
.PHONY : src/modules/core/Core.s

# target to generate assembly for a file
src/modules/core/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/core/Core.cpp.s
.PHONY : src/modules/core/Core.cpp.s

src/modules/models/request.o: src/modules/models/request.cpp.o
.PHONY : src/modules/models/request.o

# target to build an object file
src/modules/models/request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/models/request.cpp.o
.PHONY : src/modules/models/request.cpp.o

src/modules/models/request.i: src/modules/models/request.cpp.i
.PHONY : src/modules/models/request.i

# target to preprocess a source file
src/modules/models/request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/models/request.cpp.i
.PHONY : src/modules/models/request.cpp.i

src/modules/models/request.s: src/modules/models/request.cpp.s
.PHONY : src/modules/models/request.s

# target to generate assembly for a file
src/modules/models/request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/models/request.cpp.s
.PHONY : src/modules/models/request.cpp.s

src/modules/store/store.o: src/modules/store/store.cpp.o
.PHONY : src/modules/store/store.o

# target to build an object file
src/modules/store/store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/store/store.cpp.o
.PHONY : src/modules/store/store.cpp.o

src/modules/store/store.i: src/modules/store/store.cpp.i
.PHONY : src/modules/store/store.i

# target to preprocess a source file
src/modules/store/store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/store/store.cpp.i
.PHONY : src/modules/store/store.cpp.i

src/modules/store/store.s: src/modules/store/store.cpp.s
.PHONY : src/modules/store/store.s

# target to generate assembly for a file
src/modules/store/store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/store/store.cpp.s
.PHONY : src/modules/store/store.cpp.s

src/modules/tcp_server/client.o: src/modules/tcp_server/client.cpp.o
.PHONY : src/modules/tcp_server/client.o

# target to build an object file
src/modules/tcp_server/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/client.cpp.o
.PHONY : src/modules/tcp_server/client.cpp.o

src/modules/tcp_server/client.i: src/modules/tcp_server/client.cpp.i
.PHONY : src/modules/tcp_server/client.i

# target to preprocess a source file
src/modules/tcp_server/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/client.cpp.i
.PHONY : src/modules/tcp_server/client.cpp.i

src/modules/tcp_server/client.s: src/modules/tcp_server/client.cpp.s
.PHONY : src/modules/tcp_server/client.s

# target to generate assembly for a file
src/modules/tcp_server/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/client.cpp.s
.PHONY : src/modules/tcp_server/client.cpp.s

src/modules/tcp_server/common.o: src/modules/tcp_server/common.cpp.o
.PHONY : src/modules/tcp_server/common.o

# target to build an object file
src/modules/tcp_server/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/common.cpp.o
.PHONY : src/modules/tcp_server/common.cpp.o

src/modules/tcp_server/common.i: src/modules/tcp_server/common.cpp.i
.PHONY : src/modules/tcp_server/common.i

# target to preprocess a source file
src/modules/tcp_server/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/common.cpp.i
.PHONY : src/modules/tcp_server/common.cpp.i

src/modules/tcp_server/common.s: src/modules/tcp_server/common.cpp.s
.PHONY : src/modules/tcp_server/common.s

# target to generate assembly for a file
src/modules/tcp_server/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/common.cpp.s
.PHONY : src/modules/tcp_server/common.cpp.s

src/modules/tcp_server/pipe_ret_t.o: src/modules/tcp_server/pipe_ret_t.cpp.o
.PHONY : src/modules/tcp_server/pipe_ret_t.o

# target to build an object file
src/modules/tcp_server/pipe_ret_t.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/pipe_ret_t.cpp.o
.PHONY : src/modules/tcp_server/pipe_ret_t.cpp.o

src/modules/tcp_server/pipe_ret_t.i: src/modules/tcp_server/pipe_ret_t.cpp.i
.PHONY : src/modules/tcp_server/pipe_ret_t.i

# target to preprocess a source file
src/modules/tcp_server/pipe_ret_t.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/pipe_ret_t.cpp.i
.PHONY : src/modules/tcp_server/pipe_ret_t.cpp.i

src/modules/tcp_server/pipe_ret_t.s: src/modules/tcp_server/pipe_ret_t.cpp.s
.PHONY : src/modules/tcp_server/pipe_ret_t.s

# target to generate assembly for a file
src/modules/tcp_server/pipe_ret_t.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/pipe_ret_t.cpp.s
.PHONY : src/modules/tcp_server/pipe_ret_t.cpp.s

src/modules/tcp_server/tcp_client.o: src/modules/tcp_server/tcp_client.cpp.o
.PHONY : src/modules/tcp_server/tcp_client.o

# target to build an object file
src/modules/tcp_server/tcp_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/tcp_client.cpp.o
.PHONY : src/modules/tcp_server/tcp_client.cpp.o

src/modules/tcp_server/tcp_client.i: src/modules/tcp_server/tcp_client.cpp.i
.PHONY : src/modules/tcp_server/tcp_client.i

# target to preprocess a source file
src/modules/tcp_server/tcp_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/tcp_client.cpp.i
.PHONY : src/modules/tcp_server/tcp_client.cpp.i

src/modules/tcp_server/tcp_client.s: src/modules/tcp_server/tcp_client.cpp.s
.PHONY : src/modules/tcp_server/tcp_client.s

# target to generate assembly for a file
src/modules/tcp_server/tcp_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/tcp_client.cpp.s
.PHONY : src/modules/tcp_server/tcp_client.cpp.s

src/modules/tcp_server/tcp_server.o: src/modules/tcp_server/tcp_server.cpp.o
.PHONY : src/modules/tcp_server/tcp_server.o

# target to build an object file
src/modules/tcp_server/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/tcp_server.cpp.o
.PHONY : src/modules/tcp_server/tcp_server.cpp.o

src/modules/tcp_server/tcp_server.i: src/modules/tcp_server/tcp_server.cpp.i
.PHONY : src/modules/tcp_server/tcp_server.i

# target to preprocess a source file
src/modules/tcp_server/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/tcp_server.cpp.i
.PHONY : src/modules/tcp_server/tcp_server.cpp.i

src/modules/tcp_server/tcp_server.s: src/modules/tcp_server/tcp_server.cpp.s
.PHONY : src/modules/tcp_server/tcp_server.s

# target to generate assembly for a file
src/modules/tcp_server/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node_connector.dir/build.make CMakeFiles/node_connector.dir/src/modules/tcp_server/tcp_server.cpp.s
.PHONY : src/modules/tcp_server/tcp_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... node_connector"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/modules/core/Core.o"
	@echo "... src/modules/core/Core.i"
	@echo "... src/modules/core/Core.s"
	@echo "... src/modules/models/request.o"
	@echo "... src/modules/models/request.i"
	@echo "... src/modules/models/request.s"
	@echo "... src/modules/store/store.o"
	@echo "... src/modules/store/store.i"
	@echo "... src/modules/store/store.s"
	@echo "... src/modules/tcp_server/client.o"
	@echo "... src/modules/tcp_server/client.i"
	@echo "... src/modules/tcp_server/client.s"
	@echo "... src/modules/tcp_server/common.o"
	@echo "... src/modules/tcp_server/common.i"
	@echo "... src/modules/tcp_server/common.s"
	@echo "... src/modules/tcp_server/pipe_ret_t.o"
	@echo "... src/modules/tcp_server/pipe_ret_t.i"
	@echo "... src/modules/tcp_server/pipe_ret_t.s"
	@echo "... src/modules/tcp_server/tcp_client.o"
	@echo "... src/modules/tcp_server/tcp_client.i"
	@echo "... src/modules/tcp_server/tcp_client.s"
	@echo "... src/modules/tcp_server/tcp_server.o"
	@echo "... src/modules/tcp_server/tcp_server.i"
	@echo "... src/modules/tcp_server/tcp_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

